### ISSUE TITLE
Issue in FRIGGA generating MOTU table in tutorial dataset

### ISSUE THREAD

**Issue by panstrongylus** [uit-metabarcoding/MJOLNIR#3] opened 2021-11-24 10:13 UTC
Hi ! Running my data, and then the tutorial data (example_MJOLNIR_demultiplexed_data) just to check whether I had made an error - I am getting this.

**> mjolnir6_FRIGGA(lib)
FRYGGA will produce a combined file.
FRYGGA is reading the ecotag-annotated database from THOR...
FRYGGA has read the taxonomy database, with 133 total MOTUs.
FRYGGA is reading the abundances database from ODIN...
Error in read.table(abundances, sep = substr(sept, 2, 2), head = T, stringsAsFactors = F) : 
  more columns than column names
Calls: mjolnir6_FRIGGA -> read.table
Execution halted**

Looking that the abundance database there does seem to be a double ;; in there. Removing one of those unblocks it - but then you get

FRYGGA will produce a combined file.
FRYGGA is reading the ecotag-annotated database from THOR...
FRYGGA has read the taxonomy database, with 3775 total MOTUs.
FRYGGA is reading the abundances database from ODIN...
FRYGGA has read the abundances database, including 133 total MOTUs and 10 samples.
FRYGGA is done. File BATS.All_MOTUs.csv written, including 0 MOTUs with 0 total reads in 10 samples.
(0 non-singletons MOTUs).

So the outfile BATS.All_MOTUs.csv is empty and the next step (Lokki) won't run

Please help !

Many thanks

Martin

**Comment by uit-metabarcoding** [comment] 2022-01-19 15:17
This problem is caused by the use of an old version of Swarm. If any version of Swarm higher than 2.0 is installed, it will be fixed. We recommend installing the last available version of Swarm. Currently 3.1.0.

**Closed as completed** 2022-02-02 10:08 UTC
